[package]
name = "riff"
version = "0.1.1"
authors = ["Francesco Bertolaccini <bertolaccinifrancesco@gmail.com>"]
description = "This crate provides utilities for reading and writing RIFF formatted files"
repository = "https://github.com/frabert/riff"
readme = "README.md"
license = "MIT"

[badges]
travis-ci = { repository = "frabert/riff" }
codecov = { repository = "frabert/riff" }

[dependencies]
byteorder = "1"
